### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wiyegate** [android-js/androidjs-builder#17]
`
> myapp@1.0.0 build /home/chronos/user/Downloads/tmp
> androidjs build -f
{ DEBUG: false,
  BUILDER__cwd:
   '/home/chronos/user/Downloads/tmp/node_modules/androidjs-builder',
  PROJECT__cwd: '/home/chronos/user/Downloads/tmp',
  PROJECT__dist: '/home/chronos/user/Downloads/tmp/dist',
  PROJECT__DIST__name: 'dist',
  platform: 'linux',
  force_replace: true }
app core copied !
Core Modules Copied !
copying user app done.
User data copied
reading  /home/chronos/user/Downloads/tmp/dist/app-debug/AndroidManifest.xml
User assets cleared
package name com.androidjs.mypkg
{ '$': { 'android:name': 'android.permission.INTERNET' } }
android.webkit.PermissionRequest
Done!
AndroidManifest updated!
changing app name /home/chronos/user/Downloads/tmp/dist/app-debug/res/values/strings.xml
{ _: 'myapp', '$': { name: 'app_name' } }
App Name updated!
Icon updated!
Building...
I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
build process exited with code 1
Build finished!
Sign apk
stderr: provided apk path or file '/home/chronos/user/Downloads/tmp/dist/app.apk' does not exist
stderr: 
stderr: java.lang.IllegalArgumentException: provided apk path or file '/home/chronos/user/Downloads/tmp/dist/app.apk' does not exist
stderr: 
stderr: 	at at.favre.tools.apksigner.ui.FileArgParser.parseAndSortUniqueFilesNonRecursive(FileArgParser.java:38)
stderr: 
stderr: 	at at.favre.tools.apksigner.SignTool.execute(SignTool.java:63)
stderr: 
stderr: 	at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:48)
stderr: 
stderr: 	at at.favre.tools.apksigner.SignTool.main(SignTool.java:36)
stderr: 
stderr: 
Cmd history for debugging purpose:
stderr: 
sign process exited with code 1
`

**Comment by Chhekur** [comment]
Downgrade to version 1.0.6
Uninstall the current version and install

`npm install -g androidjs-builder@1.0.6`
