### ISSUE TITLE
Unable to initialize new project

### ISSUE THREAD

**Issue by uplusion23** [android-js/androidjs-builder#20]
Upon beginning a new project, entering the init command, selecting my name and type of project, the error below is shown.

```
Downloading Sample Project From:
https://raw.githubusercontent.com/android-js/sample-app/master/vue-js-example
Downloading ... ⠠
invalid github url
Failed to connect to GitHub
Check Your InterNet Connection
(node:11076) UnhandledPromiseRejectionWarning: TypeError: contents.tree is not iterable
```

**Comment by Chhekur** [comment]
Sorry for the delayed response, I hope you can understand that : )

In my case it is working fine, may be the problem is with your internet connection.
please check that out first.


Thanks

**Comment by uplusion23** [comment]
The URL in the log posts a 404. Is there a new upload?

**Comment by Chhekur** [comment]
> The URL in the log posts a 404. Is there a new upload?

If you open that link in browser then it won't work and will show 404.
But it will work find from CLI because we are directly targeting files of repo in raw format ;P
