### ISSUE TITLE
Unable to compile - bad SDK zip

### ISSUE THREAD

**Issue by danbulant** [android-js/androidjs-builder#21]
As it's stated in title, I'm getting few errors.
The first one was with the 'total' var in progress - the state.size.total was empty (when changed to 100 it worked just fine, except for percentage)
The second and for me unfixable is bad SDK zip - when the zip downloaded, it showed there's no END HEADER tag

**Comment by Chhekur** [comment]
The problem is SDK not downloaded correctly.
So you need to download that again, Please update the SDK.

`androidjs -h` for more help

**Comment by danbulant** [comment]
Oh it worked just fine on second try. But still you should fix the total

**Comment by Chhekur** [comment]
> Oh it worked just fine on second try. But still you should fix the total

We will fix it ASAP.

One more thing can you please help us to spread about `Android JS`
