### ISSUE TITLE
AndroidManifest.xml : undefined

### ISSUE THREAD

**Issue by szhatef** [android-js/androidjs-builder#24]
Hi again
It seems you updated it :) Good Job,

but it returns error for me,
BTW could you let me konw how can I set the FullScreen option by this update?

Best Regrades.

**Comment by Chhekur** [comment]
> Hi again
> It seems you updated it :) Good Job,
> 
> but it returns error for me,
> BTW could you let me konw how can I set the FullScreen option by this update?
> 
> Best Regrades.

We are updating the documentation for it, and I'll let you know once it is done ; )

**Comment by szhatef** [comment]
Unfortunately It doesn't work anymore from last day, could you please revert it to last stale version until the new update and documentations resales? 
Your project comes very handy for me, and I need to build new APKs. :)

**Comment by Chhekur** [comment]
> Unfortunately It doesn't work anymore from last day, could you please revert it to last stale version until the new update and documentations resales?
> Your project comes very handy for me, and I need to build new APKs. :)

Please update `androidjs-builder` to the latest version from `npm`

And provide the full log of error

**Comment by szhatef** [comment]
$ sudo npm install -g androidjs-builder
/usr/local/bin/androidjs -> /usr/local/lib/node_modules/androidjs-builder/test.js
+ androidjs-builder@2.0.3
updated 1 package in 4.585s

user@PC:~/Desktop/test/myfirstapp/test/hatef$ androidjs b -f
Testing 'Theme Update' ...
webview: hatef
building
updating...  [object Object]
{ fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark' }
/usr/local/lib/node_modules/androidjs-builder/lib/update_theme.js:40
                    let thm = result.resources.style[6].item;
                                     ^

TypeError: Cannot read property 'resources' of undefined
    at /usr/local/lib/node_modules/androidjs-builder/lib/update_theme.js:40:38
    at Parser.<anonymous> (/usr/local/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:310:18)
    at Parser.emit (events.js:189:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:329:16)
    at Parser.parseString (/usr/local/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:5:59)
    at ReadFileContext.callback (/usr/local/lib/node_modules/androidjs-builder/lib/update_theme.js:36:24)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:238:13)

**Comment by szhatef** [comment]
androidjs u

updating ... 
/usr/local/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55
    if ('number' != typeof options.total) throw new Error('total required');
                                          ^

Error: total required
    at new ProgressBar (/usr/local/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55:49)
    at Request.<anonymous> (/usr/local/lib/node_modules/androidjs-builder/test.js:179:23)
    at Request.emit (events.js:189:13)
    at reportState (/usr/local/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:83:21)
    at call (/usr/local/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:28:16)
    at Object.throttled [as reportState] (/usr/local/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:20:26)
    at onData (/usr/local/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:44:36)
    at IncomingMessage.emit (events.js:194:15)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)

**Comment by Chhekur** [comment]
> $ androidjs u
> 
> updating ...
> /usr/local/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55
> if ('number' != typeof options.total) throw new Error('total required');
> ^
> 
> Error: total required
> at new ProgressBar (/usr/local/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55:49)
> at Request. (/usr/local/lib/node_modules/androidjs-builder/test.js:179:23)
> at Request.emit (events.js:189:13)
> at reportState (/usr/local/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:83:21)
> at call (/usr/local/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:28:16)
> at Object.throttled [as reportState] (/usr/local/lib/node_modules/androidjs-builder/node_modules/throttleit/index.js:20:26)
> at onData (/usr/local/lib/node_modules/androidjs-builder/node_modules/request-progress/index.js:44:36)
> at IncomingMessage.emit (events.js:194:15)
> at addChunk (_stream_readable.js:284:12)
> at readableAddChunk (_stream_readable.js:265:11)

Try to run the command again, sometime this error occurs because of slow internet connection.

**Comment by szhatef** [comment]
androidjs u
updating ... 
 downloading sdk [ =========== ] 54075088/54345243 271632/bps 99% 1.0s
/usr/local/lib/node_modules/androidjs-builder/node_modules/adm-zip/adm-zip.js:22
			throw Utils.Errors.INVALID_FILENAME;
			^
Invalid filename
hatef@ZenBook:~/Desktop/test/myfirstapp/test/hatef/h$

**Comment by szhatef** [comment]
I updated it many times but each time it stuck with the error related to adm-zip.js file.

any suggestion?

**Comment by szhatef** [comment]
$ androidjs b
Testing 'Theme Update' ...
webview: test 01
building
updating...  [object Object]
{
  fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark'
}
[
  { _: '@color/colorAccent', '$': { name: 'colorAccent' } },
  { _: '@color/colorPrimary', '$': { name: 'colorPrimary' } },
  { _: '@color/colorPrimaryDark', '$': { name: 'colorPrimaryDark' } },
  { _: true, '$': { name: 'android:windowNoTitle' } },
  { _: true, '$': { name: 'android:windowFullscreen' } },
  { _: 'false', '$': { name: 'android:windowActionBar' } }
]
Done!
checking Core
using core /home/hatef/.androidjs/androidjs-sdk
removing /home/hatef/.androidjs/androidjs-sdk/assets/myapp/*
copying Assets
copying from /home/hatef/Desktop/test/myfirstapp/test 01 
to: /home/hatef/.androidjs/androidjs-sdk/assets/myapp
[ '/home/hatef/Desktop/test/myfirstapp/test 01/dist' ]
changing icon
icons Updated
changing configuration
reading  /home/hatef/.androidjs/androidjs-sdk/AndroidManifest.xml
{
  manifest: {
    '$': {
      'xmlns:android': 'http://schemas.android.com/apk/res/android',
      package: 'com.android.js.hhhh',
      platformBuildVersionCode: '28',
      platformBuildVersionName: '9'
    },
    'uses-permission': [ [Object] ],
    application: [ [Object] ]
  }
}
package name com.android.js.test 01
{ '$': { 'android:name': 'android.permission.INTERNET' } }
Done!
Updating /home/hatef/.androidjs/androidjs-sdk/res/values/strings.xml
{ _: 'test 01', '$': { name: 'app_name' } }
Building APK
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-jar',
    '/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/build_tools/apktool.jar',
    'b',
    '/home/hatef/.androidjs/androidjs-sdk',
    '-o',
    '/home/hatef/.androidjs/cache/app.apk',
    '--frame-path',
    '/home/hatef/.androidjs/cache'
  ]
}

**Comment by szhatef** [comment]
hatef@ZenBook:~/Desktop/test/myfirstapp/test 01$ androidjs u
updating ... 
㋛ using androidjs-sdk {"version":"2.0.0"}
 downloading sdk [ =========== ] 54251568/54345243 249365/bps 99% 0.4sextracting /home/hatef/.androidjs/cache/androidjs-sdk.zip androidjs-sdk-master/
done
hatef@ZenBook:~/Desktop/test/myfirstapp/test 01$ androidjs b
Testing 'Theme Update' ...
webview: test 01
building
updating...  [object Object]
{
  fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark'
}
[
  { _: '@color/colorAccent', '$': { name: 'colorAccent' } },
  { _: '@color/colorPrimary', '$': { name: 'colorPrimary' } },
  { _: '@color/colorPrimaryDark', '$': { name: 'colorPrimaryDark' } },
  { _: true, '$': { name: 'android:windowNoTitle' } },
  { _: true, '$': { name: 'android:windowFullscreen' } },
  { _: 'false', '$': { name: 'android:windowActionBar' } }
]
Done!
checking Core
using core /home/hatef/.androidjs/androidjs-sdk
removing /home/hatef/.androidjs/androidjs-sdk/assets/myapp/*
copying Assets
copying from /home/hatef/Desktop/test/myfirstapp/test 01 
to: /home/hatef/.androidjs/androidjs-sdk/assets/myapp
[ '/home/hatef/Desktop/test/myfirstapp/test 01/dist' ]
changing icon
icons Updated
changing configuration
reading  /home/hatef/.androidjs/androidjs-sdk/AndroidManifest.xml
{
  manifest: {
    '$': {
      'xmlns:android': 'http://schemas.android.com/apk/res/android',
      package: 'com.android.js.webview',
      platformBuildVersionCode: '28',
      platformBuildVersionName: '9'
    },
    'uses-permission': [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    application: [ [Object] ]
  }
}
package name com.android.js.test 01
{ '$': { 'android:name': 'android.permission.INTERNET' } }
Done!
Updating /home/hatef/.androidjs/androidjs-sdk/res/values/strings.xml
{ _: 'test 01', '$': { name: 'app_name' } }
Building APK
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-jar',
    '/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/build_tools/apktool.jar',
    'b',
    '/home/hatef/.androidjs/androidjs-sdk',
    '-o',
    '/home/hatef/.androidjs/cache/app.apk',
    '--frame-path',
    '/home/hatef/.androidjs/cache'
  ]
}
hatef@ZenBook:~/Desktop/test/myfirstapp/test 01$

**Comment by szhatef** [comment]
`hatef@ZenBook:~/Desktop/test/myfirstapp/test 01$ androidjs u
updating ... 
㋛ using androidjs-sdk {"version":"2.0.0"}
 downloading sdk [ =========== ] 54251568/54345243 249365/bps 99% 0.4sextracting /home/hatef/.androidjs/cache/androidjs-sdk.zip androidjs-sdk-master/
done
hatef@ZenBook:~/Desktop/test/myfirstapp/test 01$ androidjs b
Testing 'Theme Update' ...
webview: test 01
building
updating...  [object Object]
{
  fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark'
}
[
  { _: '@color/colorAccent', '$': { name: 'colorAccent' } },
  { _: '@color/colorPrimary', '$': { name: 'colorPrimary' } },
  { _: '@color/colorPrimaryDark', '$': { name: 'colorPrimaryDark' } },
  { _: true, '$': { name: 'android:windowNoTitle' } },
  { _: true, '$': { name: 'android:windowFullscreen' } },
  { _: 'false', '$': { name: 'android:windowActionBar' } }
]
Done!
checking Core
using core /home/hatef/.androidjs/androidjs-sdk
removing /home/hatef/.androidjs/androidjs-sdk/assets/myapp/*
copying Assets
copying from /home/hatef/Desktop/test/myfirstapp/test 01 
to: /home/hatef/.androidjs/androidjs-sdk/assets/myapp
[ '/home/hatef/Desktop/test/myfirstapp/test 01/dist' ]
changing icon
icons Updated
changing configuration
reading  /home/hatef/.androidjs/androidjs-sdk/AndroidManifest.xml
{
  manifest: {
    '$': {
      'xmlns:android': 'http://schemas.android.com/apk/res/android',
      package: 'com.android.js.webview',
      platformBuildVersionCode: '28',
      platformBuildVersionName: '9'
    },
    'uses-permission': [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    application: [ [Object] ]
  }
}
package name com.android.js.test 01
{ '$': { 'android:name': 'android.permission.INTERNET' } }
Done!
Updating /home/hatef/.androidjs/androidjs-sdk/res/values/strings.xml
{ _: 'test 01', '$': { name: 'app_name' } }
Building APK
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-jar',
    '/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/build_tools/apktool.jar',
    'b',
    '/home/hatef/.androidjs/androidjs-sdk',
    '-o',
    '/home/hatef/.androidjs/cache/app.apk',
    '--frame-path',
    '/home/hatef/.androidjs/cache'
  ]
}
hatef@ZenBook:~/Desktop/test/myfirstapp/test 01$ `

**Comment by szhatef** [comment]
$ androidjs b -f
Testing 'Theme Update' ...
webview: test 01
building
updating...  [object Object]
{
  fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark'
}
[
  { _: '@color/colorAccent', '$': { name: 'colorAccent' } },
  { _: '@color/colorPrimary', '$': { name: 'colorPrimary' } },
  { _: '@color/colorPrimaryDark', '$': { name: 'colorPrimaryDark' } },
  { _: true, '$': { name: 'android:windowNoTitle' } },
  { _: true, '$': { name: 'android:windowFullscreen' } },
  { _: 'false', '$': { name: 'android:windowActionBar' } }
]
Done!
checking Core
using core /home/hatef/.androidjs/androidjs-sdk
removing /home/hatef/.androidjs/androidjs-sdk/assets/myapp/*
(node:17877) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, unlink '/home/hatef/.androidjs/androidjs-sdk/assets/myapp/.gitignore'
    at Object.unlinkSync (fs.js:1046:3)
    at rimrafSync (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:254:15)
    at /home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:291:39
    at Array.forEach (<anonymous>)
    at rmkidsSync (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
    at rmdirSync (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
    at Object.rimrafSync [as removeSync] (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
    at /home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/lib/native_app.js:111:16
    at new Promise (<anonymous>)
    at copyCore (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/lib/native_app.js:95:12)
(node:17877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17877) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
㋛ using androidjs-sdk {"version":"2.0.0"}

**Comment by Chhekur** [comment]
> $ androidjs b -f
> Testing 'Theme Update' ...
> webview: test 01
> building
> updating... [object Object]
> {
> fullScreen: true,
> colorAccent: '@color/colorAccent',
> colorPrimary: '@color/colorPrimary',
> colorPrimaryDark: '@color/colorPrimaryDark'
> }
> [
> { _: '@color/colorAccent', '$': { name: 'colorAccent' } },
> { _: '@color/colorPrimary', '$': { name: 'colorPrimary' } },
> { _: '@color/colorPrimaryDark', '$': { name: 'colorPrimaryDark' } },
> { _: true, '$': { name: 'android:windowNoTitle' } },
> { _: true, '$': { name: 'android:windowFullscreen' } },
> { _: 'false', '$': { name: 'android:windowActionBar' } }
> ]
> Done!
> checking Core
> using core /home/hatef/.androidjs/androidjs-sdk
> removing /home/hatef/.androidjs/androidjs-sdk/assets/myapp/*
> (node:17877) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, unlink '/home/hatef/.androidjs/androidjs-sdk/assets/myapp/.gitignore'
> at Object.unlinkSync (fs.js:1046:3)
> at rimrafSync (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:254:15)
> at /home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:291:39
> at Array.forEach ()
> at rmkidsSync (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:291:26)
> at rmdirSync (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:281:7)
> at Object.rimrafSync [as removeSync] (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/fs-extra/lib/remove/rimraf.js:252:7)
> at /home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/lib/native_app.js:111:16
> at new Promise ()
> at copyCore (/home/hatef/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/lib/native_app.js:95:12)
> (node:17877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:17877) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ㋛ using androidjs-sdk {"version":"2.0.0"}

Run command as a root, error occurs because of permission issue.

**Comment by szhatef** [comment]
I reinstall my OS , now I have other problems:
 

sudo androidjs b -f
Testing 'Theme Update' ...
webview: hatef
building
updating...  [object Object]
{
  fullScreen: true,
  colorAccent: '@color/colorAccent',
  colorPrimary: '@color/colorPrimary',
  colorPrimaryDark: '@color/colorPrimaryDark'
}
/usr/lib/node_modules/androidjs-builder/lib/update_theme.js:40
                    let thm = result.resources.style[6].item;
                                     ^

TypeError: Cannot read property 'resources' of undefined
    at /usr/lib/node_modules/androidjs-builder/lib/update_theme.js:40:38
    at Parser.<anonymous> (/usr/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:310:18)
    at Parser.emit (events.js:209:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:329:16)
    at Parser.parseString (/usr/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:5:59)
    at ReadFileContext.callback (/usr/lib/node_modules/androidjs-builder/lib/update_theme.js:36:24)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:250:13)

**Comment by Chhekur** [comment]
> I reinstall my OS , now I have other problems:
> 
> sudo androidjs b -f
> Testing 'Theme Update' ...
> webview: hatef
> building
> updating... [object Object]
> {
> fullScreen: true,
> colorAccent: '@color/colorAccent',
> colorPrimary: '@color/colorPrimary',
> colorPrimaryDark: '@color/colorPrimaryDark'
> }
> /usr/lib/node_modules/androidjs-builder/lib/update_theme.js:40
> let thm = result.resources.style[6].item;
> ^
> 
> TypeError: Cannot read property 'resources' of undefined
> at /usr/lib/node_modules/androidjs-builder/lib/update_theme.js:40:38
> at Parser. (/usr/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:310:18)
> at Parser.emit (events.js:209:13)
> at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:329:16)
> at Parser.parseString (/usr/lib/node_modules/androidjs-builder/node_modules/xml2js/lib/parser.js:5:59)
> at ReadFileContext.callback (/usr/lib/node_modules/androidjs-builder/lib/update_theme.js:36:24)
> at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:250:13)

We are trying to find the bug...
Can you please post your `package.json` file here ?

**Comment by Chhekur** [comment]
Okay so `package.json` looks fine, so there is a bug in `builder`, we are trying to find that out.

**Comment by SharifPoetra** [comment]
> ```/usr/lib/node_modules/androidjs-builder/lib/update_theme.js:40
let thm = result.resources.style[6].item;
^

TypeError: Cannot read property 'resources' of undefined``` is this still not fixed?

**Comment by PassionPenguin** [comment]
with the same problem
