### ISSUE TITLE
 Cannot read property 'resources' of undefined

### ISSUE THREAD

**Issue by ChineseOuchie** [android-js/androidjs-builder#29]
When running ```androidjs build -f``` I get this following error

```
let thm = result.resources.style[6].item;
                                     ^

TypeError: Cannot read property 'resources' of undefined```

**Comment by ChineseOuchie** [comment]
I'm missing everything from `res/values/styles.xml`

**Comment by ChineseOuchie** [comment]
After adding the missing files I get this following error:

```events.js:174
      throw er; // Unhandled 'error' event
      ^```

I copied the missing files from my computer where it does work, but it isn't working on my laptop

**Comment by Chhekur** [comment]
Delete the androidjs sdk and try download again

**Comment by ChineseOuchie** [comment]
Delete the androidjs-sdk folder?

**Comment by Chhekur** [comment]
Go to your users folder and then delete .androidjs folder

**Comment by ChineseOuchie** [comment]
When deleted I get this error again: 
```
let thm = result.resources.style[6].item;
                                     ^

TypeError: Cannot read property 'resources' of undefined```
```

**Comment by Chhekur** [comment]
Had sdk downloaded properly?

**Comment by ChineseOuchie** [comment]
No, still no sdk

**Comment by Chhekur** [comment]
Generate project using androidjs init command and then try to build it will automatically download sdk from internet

**Comment by ChineseOuchie** [comment]
Still no sdk

And I got this following error using the init command
```
403/403 ✔ vue-js-example/node_modules/socket.io-client/dist/socket.io.dev.js
example downloaded
fs.js:114
    throw err;
    ^
```

**Comment by Chhekur** [comment]
Can you please provide full log?

**Comment by ChineseOuchie** [comment]
I do have SDK now after doing the build command but I have a new error. See Below

This is what I get from ini command:

```
example downloaded
fs.js:114
    throw err;
    ^

Error: EPERM: operation not permitted, rename 'D:\projects\a\vue-js-example' -> 'D:\projects\a\tttt'
    at Object.renameSync (fs.js:598:3)
    at copy.fromGithub.to (C:\Users\Joey\AppData\Roaming\npm\node_modules\androidjs-builder\lib\native_app.js:45:20)
    at Request.request [as _callback] (C:\Users\Joey\AppData\Roaming\npm\node_modules\androidjs-builder\lib\copy.js:115:44)
    at Request.self.callback (C:\Users\Joey\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Users\Joey\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:203:15)
    at IncomingMessage.<anonymous> (C:\Users\Joey\AppData\Roaming\npm\node_modules\androidjs-builder\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
```

And this is from `androidjs build -f`
```
Testing 'Theme Update' ...
webview: vue_example
building
updating...  [object Object]
theme attribute not found in package.json
checking Core
https://github.com/android-js/androidjs-sdk/archive/master.zip
 downloading sdk [ =======================================  ] 52604836/54345243 1545746/bps 96% 1.1s done
extracting: https://github.com/android-js/androidjs-sdk to: C:\Users\Joey\.androidjs\androidjs-sdk
 ✔ done
copying Assets
copying from D:\projects\a\vue-js-example
to: C:\Users\Joey\.androidjs\androidjs-sdk\assets\myapp
[ 'D:\\projects\\a\\vue-js-example\\dist' ]
changing icon
icons Updated
changing configuration
reading  C:\Users\Joey\.androidjs\androidjs-sdk\AndroidManifest.xml
{ manifest:
   { '$':
      { 'xmlns:android': 'http://schemas.android.com/apk/res/android',
        package: 'com.android.js.webview',
        platformBuildVersionCode: '28',
        platformBuildVersionName: '9' },
     'uses-permission':
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     application: [ [Object] ] } }
package name com.android.js.hello
{ '$': { 'android:name': 'android.permission.INTERNET' } }
Done!
Updating C:\Users\Joey\.androidjs\androidjs-sdk\res\values\strings.xml
{ _: 'Vue Example', '$': { name: 'app_name' } }
Building APK
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)


Testing 'Theme Update' ...
webview: vue_example
building
updating...  [object Object]
theme attribute not found in package.json
checking Core
https://github.com/android-js/androidjs-sdk/archive/master.zip
 downloading sdk [ =======================================  ] 52604836/54345243 1545746/bps 96% 1.1s done
extracting: https://github.com/android-js/androidjs-sdk to: C:\Users\Joey\.androidjs\androidjs-sdk
 ✔ done
copying Assets
copying from D:\projects\a\vue-js-example
to: C:\Users\Joey\.androidjs\androidjs-sdk\assets\myapp
[ 'D:\\projects\\a\\vue-js-example\\dist' ]
changing icon
icons Updated
changing configuration
reading  C:\Users\Joey\.androidjs\androidjs-sdk\AndroidManifest.xml
{ manifest:
   { '$':
      { 'xmlns:android': 'http://schemas.android.com/apk/res/android',
        package: 'com.android.js.webview',
        platformBuildVersionCode: '28',
        platformBuildVersionName: '9' },
     'uses-permission':
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     application: [ [Object] ] } }
package name com.android.js.hello
{ '$': { 'android:name': 'android.permission.INTERNET' } }
Done!
Updating C:\Users\Joey\.androidjs\androidjs-sdk\res\values\strings.xml
{ _: 'Vue Example', '$': { name: 'app_name' } }
Building APK
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Chhekur** [comment]
You can manually rename the folder, this error generally occurs in windows

**Comment by ChineseOuchie** [comment]
Which folder do I need to rename?

**Comment by Chhekur** [comment]
Your project folder along with package json file

**Comment by ChineseOuchie** [comment]
Still have this error while building
```
events.js:174
      throw er; // Unhandled 'error' event
```

**Comment by ChineseOuchie** [comment]
I have the same problem in Ubuntu

**Comment by Chhekur** [comment]
Are you using latest version of androidjs and androidjs-builder

**Comment by ChineseOuchie** [comment]
androidjs 1.0.5

builder 2.0.3

Which are the same on both devices

**Comment by Chhekur** [comment]
Do you have java installed on your system?
JDK >= 1.8

**Comment by ChineseOuchie** [comment]
That one fixed it. I didn't have Java on my laptop.

**Comment by Chhekur** [comment]
> That one fixed it. I didn't have Java on my laptop.

It requires java because it uses tools which are based on java such as : gradle

**Comment by ChineseOuchie** [comment]
Didn't know that because I saw nothing about Java in the Docs.

**Comment by Chhekur** [comment]
> Didn't know that because I saw nothing about Java in the Docs.

We'll mention that into docs ; )

**Comment by liojulien** [comment]
Hello there,i am newbie, i have yet applyed what is in doc using vscode and androidjs to build an android app and i get all type of errors that here i found solutions but the last issue is about java :
error: spawn java ENOENT, for this one only thing i have to do is to set the path for java jdk and then the project work fine!

**Comment by yanickrochon** [comment]
I have Java on my machine, and still get this error. I *just* downloaded everything and used the `androidjs init` to generate a brand new project... nothing was added or removed.

Java 1.8 installed, `JAVA_HOME` is set as well as `ANDROID_HOME` (pointing to the Android SDK), etc.

Also on Ubuntu.

When running `androidjs update` I also get 

```
Error: total required
    at new ProgressBar (/home/thermo/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55:49)
    at Request.<anonymous> (/home/thermo/.nvm/versions/node/v12.10.0/lib/node_modules/androidjs-builder/test.js:179:23)
```

I have no idea why I'm getting this.

**Comment by Chhekur** [comment]
> I have Java on my machine, and still get this error. I _just_ downloaded everything and used the `androidjs init` to generate a brand new project... nothing was added or removed.
> 
> Java 1.8 installed, `JAVA_HOME` is set as well as `ANDROID_HOME` (pointing to the Android SDK), etc.
> 
> Also on Ubuntu.
> 
> When running `androidjs update` I also get
> 
> ```
> Error: total required
>     at new ProgressBar (/home/.../node/v12.10.0/lib/node_modules/androidjs-builder/node_modules/progress/lib/node-progress.js:55:49)
>     at Request.<anonymous> (/home/.../node/v12.10.0/lib/node_modules/androidjs-builder/test.js:179:23)
> ```
> 
> I have no idea why I'm getting this.

In order to solve `total required` error, you can repeatedly run `update` command until it starts downloading ; )

Feel free to ask in case of any problem

**Comment by kaippally** [comment]
Hello
Tried to build https://github.com/android-js/sample-app/tree/master/helloworld

but I get this :

`copying assets ...
updating app name...
Setting app version ...
Version Code: 1000032
Version Name: 1.0.0
updating theme ...
theme attribute not found in package.json
Using SDK: 2.1.0
Building Apk ...
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: [
    '-jar',
    'C:\\Users\\Nishad\\AppData\\Roaming\\npm\\node_modules\\androidjs-builder\\build_tools\\apktool.jar',
    'b',
    'C:\\Users\\Nishad\\.androidjs\\cache\\androidjs-sdk',
    '-o',
    'C:\\Users\\Nishad\\.androidjs\\cache\\myapp.apk',
    '--frame-path',
    'C:\\Users\\Nishad\\.androidjs\\cache'
  ]
}`

Am I missing something?
