### ISSUE TITLE
Can I set targetSdkVersion to custom value?

### ISSUE THREAD

**Issue by y-ich** [android-js/androidjs-builder#40]
Hello.
Thank you for your great project!

Current version of Android JS builder sets targetSdkVersion to 30.
I want to set it to 28.
Could you tell me the easy way if possible?
(I saw an article to change it in StackOverflow, it requires re-signing.)

Thanks.

**Comment by y-ich** [comment]
It was resolved by installing androidjs-builder@2.1.8, though my real problem, that I want to execute an executable binary in debug release of my app, is not solved yet.

**Comment by y-ich** [comment]
Sorry, I misunderstood platformBuildVersionCode as targetSdkVersion.
The question of this issue is still alive.

**Comment by Chhekur** [comment]
Hey @y-ich could you elaborate more, like why do you want it to set  `28`?

**Comment by y-ich** [comment]
Hi, @Chhekur san.

I want to execute an executable binary in my personal app, which is an experimental prototype, not for release on Google Play.
Making lib*.so from it and preparing FFI for it seem cumbersome.

**Comment by Chhekur** [comment]
Hi @y-ich, yeah I get it that you want to execute some specific binary but I mean what is the exact problem you are facing? then I might help you better.

**Comment by y-ich** [comment]
I am sorry that I don't understand what you are saying well.
I really want to execute my executable binary in my prototype app.
You know, if you set targetSdkVersion to 29 or later, you have no execute permissions for app home directory.

Removed execute permission for app home directory https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission

**Comment by Chhekur** [comment]
Hey @y-ich, we haven't encountered anything like that yet, so we don't have anything specific for the same right now,
but what you can do is, you can change the update the `apktool.yml` inside the `Android JS SDK` and then try rebuilding and resign your app.

**Comment by y-ich** [comment]
@Chhekur san, I see and anyway thank you for your response!
Good luck for your nice project!
